version: "3.0"

services:
  db:
    image: mysql:8.0
    container_name: fitti-mysql
    hostname: fitti-mysql
    deploy:
      placement:
        constraints:
          - node.role = manager
    environment:
      TZ: Asia/Seoul
      MYSQL_ROOT_PASSWORD: fitti
      MYSQL_USER: fitti
      MYSQL_PASSWORD: fitti
    #      MYSQL_ROOT_USER: root

    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h","localhost" ]
    ports:
      - "5515:3306"
    restart: unless-stopped
    volumes:
      - fitti-mysql_volume:/var/lib/mysql
      - ./docker/init-database.sql:/docker-entrypoint-initdb.d/init-database.sql

volumes:
  fitti-mysql_volume:
