spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "977472810181-9c5lhmghkq0d08mu864jdphg4236ltbm.apps.googleusercontent.com"
            client-secret: "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"
            scope: email, profile

  datasource:
    username: fitty
    password: fitty
    engine: mysql
    host: localhost
    port: 5515
    dbname: fitty_database
