spring:
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: "937430724441233"
            client-secret: "b45e1c38c53967f1722591140db50afa"
            #            redirect-uri: "{baseUrl}/login/oauth2/code/facebook"
            redirect-uri: "http://localhost:8080/login/oauth2/code/facebook"
            #            authorization-grant-type: authorization_code
            scope:
              - email
              - public_profile
          #            client-name: Facebook
          naver:
            client-id: "idvEjrVyEM0SM7AtoSz_"
            client-secret: "fVmGtsHZfp"
            #            redirect-uri: "{baseUrl}/login/oauth2/code/naver"
            redirect-uri: "http://localhost:8080/login/oauth2/code/naver"
            authorization-grant-type: authorization_code
            scope:
              - profile_image
              - profile
              - email
              - name
            client-name: Naver

          google:
            client-id: "145831654696-kk74q7hpk53qkg8c16lpcal6fqn94rrg.apps.googleusercontent.com"
            client-secret: "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"
            scope:
              - email
              - profile
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
#        kakao는 email을 제공하지 않아서 제외 후에 앱 배포후 추가예정. todo

