spring:
  application:
    name: Fitty API Develop
  datasource:
    hikari:
      minimum-idle: 0
      max-lifetime: 600000
      idle-timeout: 300000
    username: ${USER_NAME}
    password: ${PASSWORD}
    engine: ${ENGINE}
    host: ${HOST}
    port: ${DB_PORT}
    dbname: ${DB_NAME}

management:
  health:
    db:
      enabled: false
