spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_PASSWORD}
  datasource:
    username: fitty
    password: fitty
    engine: mysql
    host: localhost
    port: 5515
    dbname: fitty_database
