spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_PASSWORD}
            scope: email, profile
  application:
    name: Fitty API Develop
  datasource:
    hikari:
      minimum-idle: 0
      max-lifetime: 600000
      idle-timeout: 300000
    username: ${USER_NAME}
    password: ${PASSWORD}
    engine: ${ENGINE}
    host: ${HOST}
    port: ${DB_PORT}
    dbname: ${DB_NAME}

server:
  port: 5000 # AWS Nginx default port
  tomcat:
    remoteip:
      protocol-header: x-forwarded-proto
      remote-ip-header: x-forwarded-for
    accesslog:
      enabled: true
      pattern: "%{X-Forwarded-For}i (, %h) %l %u %t &quot;%r&quot; %s %b"

management:
  health:
    db:
      enabled: false
