name: Resend Review Requests
on:
  pull_request:
    branches-ignore:
      - release
      - main
    types: [ synchronize ]

jobs:
  resend_review_requests:
    runs-on: ubuntu-latest
    steps:
      - name: Resend review requests
        run: |
          PR_NUMBER=$(echo "${GITHUB_REF}" | sed -e 's,.*/pull/\([0-9]*\)/.*,\1,')
          PR_AUTHOR=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${PR_NUMBER} | jq -r '.user.login')
          REVIEWED_USERS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${PR_NUMBER}/reviews | jq --arg author "$PR_AUTHOR" -r '.[] | select(.user.login != $author) | .user.login' | sort -u | awk '{printf "\"%s\",", $0}' | sed 's/,$//')
          curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -X POST https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${PR_NUMBER}/requested_reviewers --data "{\"reviewers\": [${REVIEWED_USERS}]}"
