name: Auto reviewer
on:
  pull_request:
    branches-ignore:
      - release
      - main
    types: [ opened, ready_for_review, reopened ]
  push:

jobs:
  set_reviewers:
    name: Auto reviewer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Request review
        uses: necojackarc/auto-request-review@v0.12.0
        with:
          token: ${{ secrets.PAT_FITTY }}
          config: .github/reviewers/reviewers.yml
          use_local: true
